### ISSUE TITLE
Timeline for new release

### ISSUE THREAD

**Issue by berceanu** [yt-project/unyt#100]
Is there a timeline for the next release? It would help me to plan downstream releases a bit :)

**Comment by ngoldbaum** [comment]
We don't have a specific timeline for a release. If you'd like me to do a release I can do that, it takes an hour or so.

**Comment by berceanu** [comment]
That would be great, whenever you find the time :) And please let me know if I can help!

**Comment by berceanu** [comment]
You rock :heart:
