### ISSUE TITLE
Equality test of equivalent quantities, but with different prefixes, returns False.

### ISSUE THREAD

**Issue by l-johnston** [yt-project/unyt#118]
* unyt version: 2.4.1
* Python version: 3.8.1
* Operating System: Win10

### Description

The quantities 1 s and 1000 ms are equal, but unyt says they're not equal.

### What I Did

```
>>> from unyt import s, ms
>>> 1*s == 1000*ms
array(False)
```
I also find the rather surprising result:
```
>>> 1*s >= 999*ms
array(True)
>>> 1*s >= 1000*ms
array(False)

**Comment by ngoldbaum** [comment]
Hmm, that's strange, I'm not able to reproduce this.

What sympy version are you using?

**Comment by ngoldbaum** [comment]
Also if you try this using unyt 2.4.0 does it work properly?

**Comment by ngoldbaum** [comment]
I'm using python 3.8.1, sympy 1.5.1, and numpy 1.18.1 and unyt 2.4.1 over here's what I get running your test snippets:

```
In [1]: from unyt import s, ms

In [2]: 1*s == 1000*ms
Out[2]: array(True)

In [3]: 1*s >= 999*ms
Out[3]: array(True)

In [4]: 1*s >= 1000*ms
Out[4]: array(True)
```

**Comment by l-johnston** [comment]
I am using sympy 1.5 and numpy 1.18.0

**Comment by ngoldbaum** [comment]
Hmm, still not able to reproduce using those versions of sympy and numpy. Maybe it's windows-specific? I don't have a windows machine to test on.

**Comment by l-johnston** [comment]
Appears to be a Windows thing. On Linux, I get your result.

**Comment by ngoldbaum** [comment]
I just tried on a windows 10 machine and unfortunately I'm still not able to reproduce this behaviour. If anyone else is seeing this more details would be really helpful.

**Comment by l-johnston** [comment]
I have run it on three different Win10 machines each returning False. I have set up a unyt dev to step through the code.

**Comment by ngoldbaum** [comment]
How did you set up Python on those machines? I was testing using python and dependencies installed via conda-forge.

**Comment by l-johnston** [comment]
On two of the machines, here are the steps:
- install Python 3.8.1 from python.org
- create a virtual env and activate
- upgrade pip
- pip install unyt
- python
>>> from unyt import s, ms
>>> 1*s == 1000*ms
array(False)

**Comment by l-johnston** [comment]
The problem appears to be a numerical precision issue. In the array.py file and __array_ufunc__, there is a conversion factor of 0.001 for the 1000*ms and on these machines, 1000 * 0.001 gives 1.0000000474974513 which causes the False result.

**Comment by ngoldbaum** [comment]
Ah, interesting. I was just now able to reproduce this. Another fun aspect is that `1000*ms == 1*s` returns True.

I'm not entirely sure what we can do about this without adding tons of hacks.

**Comment by ngoldbaum** [comment]
Here's another fun one:

```
In [15]: 1*s - 1000*ms
Out[15]: unyt_quantity(-4.74974513e-08, 's')

In [16]: 1.*s - 1000.*ms
Out[16]: unyt_quantity(0., 's')
```

So maybe if we need to coerce data to a float dtype the correct thing is to coerce first, *then* multiply by the conversion factor.

All of this is happening because the default float dtype on windows is float32.

**Comment by l-johnston** [comment]
perhaps make both the same type:
np.float32(0.001) * np.float32(1000) = 1.0

**Comment by ngoldbaum** [comment]
I opened #119 with a fix.
