### ISSUE TITLE
Would you be at all interested in adding a `name` field to the `unyt.unyt_array` class?

### ISSUE THREAD

**Issue by l-johnston** [yt-project/unyt#128]
Would you be at all interested in adding a `name` field to the `unyt.unyt_array` class? I have implemented in this in a few libraries that use `unyt` and find it very useful. Then you can, on these axes, use the names of the (last) arrays that were plotted to form the axes labels.

...

_Originally posted by @JBorrow in https://github.com/yt-project/unyt/issues/125#issuecomment-576899749_

**Comment by JBorrow** [comment]
Thanks for opening this!

**Comment by l-johnston** [comment]
I have implemented this feature and now the axis label will include the array name:

```python
>>> from unyt import *
>>> import matplotlib.pyplot as plt
>>> matplotlib_support.enable()
>>> matplotlib_support.label_style = "[]"
>>> x = [0,1,2]*s
>>> x.name = "Time"
>>> y = [3,4,5]*m
>>> y.name = "Distance"
>>> plt.plot(x, y)
>>> plt.show()
```
![fig5](https://user-images.githubusercontent.com/17813788/72892865-3dc54980-3cdd-11ea-8a6a-ec357f1c8c3d.png)

**Comment by JBorrow** [comment]
Can you also pass a `name` keyword to the `unyt_array` constructor?

So:
```python
x = unyt.unyt_array([1,2,3], units="kpc", name="Radii")
```

**Comment by JBorrow** [comment]
P.s. this is great!

**Comment by l-johnston** [comment]
> 
> 
> Can you also pass a `name` keyword to the `unyt_array` constructor?
> 
> So:
> 
> ```python
> x = unyt.unyt_array([1,2,3], units="kpc", name="Radii")
> ```

possible, but I'd like to hear from @ngoldbaum first.
