### ISSUE TITLE
np.histogram does not support unyt_array

### ISSUE THREAD

**Issue by l-johnston** [yt-project/unyt#130]
* unyt version: 2.5.0
* Python version: 3.6.9
* Operating System: Linux

### Description

Computing a histogram where both the input data and range parameters are both of unyt_array type crashes. See [numpy issue 15437](https://github.com/numpy/numpy/issues/15437) for discussion there.

### What I Did

```
>>> import numpy as np
>>> from unyt import unyt_array
>>> x = unyt_array(np.random.normal(size=1000), "m")
>>> np.histogram(x, bins=10, range=(x.min(), x.max()))
```

This issue causes matplotlib's histogram to fail - even without matplotlib_support enabled.

```
>>> import matplotlib.pyplot as plt
>>> from unyt import m
>>> import numpy as np
>>> x = np.random.normal(size=1000)*m
>>> plt.hist(x)
```

**Comment by ngoldbaum** [comment]
For what it’s worth I’m planning on taking a first pass on implementing `__array_function__` for `unyt_array`, that said it’s probably not correct for numpy to error like that for operands that do not implement `__array_function__`.
