### ISSUE TITLE
Unyt does not support the units neper and bel for logarithmic quantities.

### ISSUE THREAD

**Issue by l-johnston** [yt-project/unyt#132]
### Feature Proposal
The logarithmic quantities level-of-power and level-of-field are commonly used in engineering, defined in IEC 60027-3, and accepted for use with the SI. I propose defining the dimension ``(logarithmic)`` and add the units bel and neper to Unyt. I have implemented this in my [logarithmic_quantities](https://github.com/l-johnston/unyt/tree/logarithmic_quantity) branch. Some examples with this implementation:
```
>>> import numpy as np
>>> from unyt import Np, B, dB, mW, V
>>> B.dimensions
(logarithmic)
>>> B.get_base_equivalent()
Np
>>> p = [1, 100]*mW
>>> p_0 = 1*mW
>>> level_of_power = np.log10(p/p_0)*B
>>> level_of_power
unyt_array([0., 2.], 'B')
>>> level_of_power.to("dB")
unyt_array([ 0., 20.], 'dB')
>>> f = [1, 10]*V
>>> f_0 = 1*V
>>> level_of_field = 20*np.log10(f/f_0)*dB
>>> level_of_field
unyt_array([ 0., 20.], 'dB')
>>> 10**(level_of_field.v/20)*f_0
unyt_array([ 1., 10.], 'V')
>>> (1*B)/(np.log(10)/2) == 1*Np
array(True)
```
Is the Unyt team interested in this feature?

**Comment by ngoldbaum** [comment]
Seems fine to me!

Probably needs some discussion in the docs though.
