### ISSUE TITLE
Pickled arrays override lookup tables for symbols

### ISSUE THREAD

**Issue by matthewturk** [yt-project/unyt#136]
* unyt version: 15b812b4ead42403073847ad655569e48a639378
* Python version: 3.7
* Operating System: linux

### Description

This is a minimal worked example of the answer test failures described in yt-project/yt#2437 .  The answer testing framework utilizes `shelve`, so exercises `__setstate__` functionality on `unyt_array` via pickle.

This shows up in yt because internally to yt 3.x the base unit system is CGS and in unyt it is now MKS, but it does not require this to be the case.  Note that in the snapshot below, removing the `unit_system` argument produces the same result.

### What I Did

```
lut_old = {'cm': (1.00, sympy.sympify("(length)"), 0.0, '\\rm{cm}', False)}
lut_new = {'cm': (0.01, sympy.sympify("(length)"), 0.0, '\\rm{cm}', False)}

reg_old = unyt.UnitRegistry(lut=lut_old, add_default_symbols=False, unit_system="cgs")
reg_new = unyt.UnitRegistry(lut=lut_new, add_default_symbols=False, unit_system="mks")

q_old = unyt.unyt_quantity(1.0, 'cm', registry = reg_old)
q_new = unyt.unyt_quantity(1.0, 'cm', registry = reg_new)

print(q_old - q_new)

```

This produces `0.99 cm` when I would expect it to be `0.0 cm`.

Thanks to @xarthisius for working through this all with me.

**Comment by ngoldbaum** [comment]
Is there any chance you can share one of the old answer files that are getting loaded? I think we might be able to reuse the code for loading JSON unit registries from `yt.units` in the pickle code, but this example isn't quite the same case as what's happening in the yt CI so it's a little hard for me to reason about.

In particular, I don't think it's correct to ignore data that's stored in unit registries like we'd have to do with the given example. Instead I think we should detect that we've been handed a pickle generated with `yt.units` and do the correction only for that case.

**Comment by Xarthisius** [comment]
http://use.yt/upload/d979a4f3 - answer tests for Flash. This is what we were using while debuging.

**Comment by ngoldbaum** [comment]
Thanks!

**Comment by Xarthisius** [comment]
This test is also the most convenient:

```
import shelve
dd = shelve.open("py35_local_flash_009")
run = dd["sloshing_low_res_hdf5_plt_cnt_0300"]
le = run["GridHierarchy_sloshing_low_res_hdf5_plt_cnt_0300_all"]["grid_left_edges"][0]
```
