### ISSUE TITLE
Sympy lambdify gives inconsistent results with Unyt objects

### ISSUE THREAD

**Issue by l-johnston** [yt-project/unyt#138]
* unyt version: 2.6.0
* sympy version: 1.5.1
* Python version: 3.8.1
* Operating System: Linux

### Description
Some sympy expressions yield lambdified functions that work with unyt quantities in that they will accept and return unyt quantities. But other expressions will strip the unit and return ndarray.

### What I Did
An expression that works:
```
>>> from sympy import symbols, lambdify
>>> from unyt import V
>>> v1, v2 = symbols("v1 v2")
>>> expr = v1 + v2
>>> args = list(expr.free_symbols)
>>> args
[v1, v2]
>>> f = lambdify(args, expr)
>>> f(1*V, 2*V)
unyt_quantity(3, 'V')
```

An expression that doesn't work:
```
>>> from sympy import symbols, lambdify, Piecewise
>>> from unyt import V
>>> v1, v2 = symbols("v1 v2")
>>> expr = Piecewise((v2, v2 > v1), (v1, True))
>>> args = list(expr.free_symbols)
[v1, v2]
>>> f = lambdify(args, expr)
>>> f(1*V, 2*V)
array(2.)
```

**Comment by ngoldbaum** [comment]
I don’t know if there’s much we can do about this. I’m a little surprised it works at all actually, sympy doesn’t know anything about our types.

**Comment by ngoldbaum** [comment]
In fact, I bet you’d see the same behavior with any ndarray subclass.

**Comment by ngoldbaum** [comment]
Yeah, take a look at this:

```
from sympy import symbols, lambdify, Piecewise
import numpy as np
class myarray(np.ndarray):
    pass

data = np.array([1, 2, 3]).view(myarray)

v1, v2 = symbols("v1 v2")
expr = Piecewise((v2, v2 > v1), (v1, True))
args = list(expr.free_symbols)
f = lambdify(args, expr)

print(f(data, data), type(f(data, data)))

expr = v1 + v2
args = list(expr.free_symbols)
f = lambdify(args, expr)

print(f(data, data), type(f(data, data)))
```

This prints: 
```
[1. 2. 3.] <class 'numpy.ndarray'>
[2 4 6] <class '__main__.myarray'>
```

I'm gonna close this, I think you might want to report this against sympy.

**Comment by l-johnston** [comment]
Well, not so fast. I believe if Unyt supported __array_func__, that it would work. Sympy takes the Piecewise function and converts it to np.select().
```
>>> from sympy import symbols, lambdify, Piecewise
>>> v1, v2 = symbols("v1 v2")
>>> expr = Piecewise((v2, v2>v1), (v1, True))
>>> args = list(expr.free_symbols)
>>> f = lambdify(args, expr)
>>> import inspect
>>> inspect.getsource(f)
'def _lambdifygenerated(v1, v2):\n    return (select([less(v1, v2),True], [v2,v1], default=nan))\n'
```

**Comment by ngoldbaum** [comment]
Ah, well there you go :)

Still, `__array_function__` support is a separate issue. One that's very much on my radar, though.

**Comment by l-johnston** [comment]
I am willing to work on `__array_function__`.

**Comment by ngoldbaum** [comment]
Thanks for the offer, I’m planning to work on it soon. I’ll let you know if plans change along those lines.
