### ISSUE TITLE
"mu," fonts in matplotlib, and unicode fallbacks

### ISSUE THREAD

**Issue by matthewturk** [yt-project/unyt#145]
The "mu" unicode character seems to have some interesting things going on in matplotlib.  I'm not issuing a pull request because I have a suspicion that there are more complex things going on than I realize.

matplotlib uses the `FT_get_glyph_index` function when it's attempting to identify a symbol, and then uses the result of that to identify the appropriate replacement for fallbacks.  Using the `cm` font system, this shows up when using unicode characters.

The subtlety seems to show up when using `\u00b5` versus `\u03bc` to represent the mu character.  In `unyt/_unit_lookup_table.py`, both b5 and3bc show up in the `unit_prefixes`.  (As a sidenote, I think evidence of the problem is visible in vim if you search for u00b5 and u03bc -- searching for the former includes the latter, but not the reverse.)  Elsewhere in the code, 00b5 shows up in things like `generate_name_alternatives` etc, but u03bc does not.

The problem comes in in that the `used_prefix` is *replaced* with u00b5.  This character returns a *positive* in `FT_get_glyph_index`, so it does *not* trigger the "replace with a symbol from STIX" code path in matplotlib, and instead thinks it has correctly identified the glyph as "grave" (backtick I think).  So it proceeds using this as the symbol instead of using the backup symbol.

What I *think* is the "pragmatic" way forward would be to swap everything for u03bc, and reverse the behavior.  Unfortunately, my reading of the codenames in Unicode (which are emphasized in `_unit_lookup_table.py` as drawn from Juan Reyero) is that the *correct* one is really u00b5, and u03bc really is what should be the more specific implementation...  So I'm not sure even what to suggest, since it kind of reads to me like we're bumping up at the ugly space between pragmatism and idealism.

Anyway here's a script that demonstrates:

```
mport matplotlib.pyplot as plt
import numpy as np
from matplotlib.style import context
style = {
    'mathtext.fontset': 'cm',
    'mathtext.fallback_to_cm': True,
}
with context(style, after_reset=False):
    labels = ['$\\rm{x\\ \\ (\\rm{' + '\u03bc' + 'm})}$', '$\\rm{y\\ \\ (\\rm{' + '\u00b5' + '})}$']
    t = np.arange(0.0, 2.0, 0.01)
    s = 1 + np.sin(2 * np.pi * t)
    fig, ax = plt.subplots()
    ax.plot(t, s)
    ax.set(xlabel=labels[0], ylabel=labels[1],
           title='About as simple as it gets, folks')
    ax.grid()
    fig.savefig("test.png")
```

**Comment by ngoldbaum** [comment]
I would personally say, having not thought about this at all, is doing the pragmatic thing makes a lot of sense: just use whichever unicode variant people actually use for this and that has good support in common fonts.

Another option: is it possible to catch this in the matplotlib converter code inside of unyt when generating the labels?

**Comment by langmm** [comment]
Just a note in case anyone else encounters this issue:

On Windows the new default mu character '\u03bc' does not appear to be part of the Latin alphabet code page (1252) which I think is the default for English and a few other languages. The result of printing this character is an error concluding with:

```
  File "c:\miniconda3-x64\envs\test-environment\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u03bc' in position 23: character maps to <undefined>
```

**Comment by ngoldbaum** [comment]
@langmm hmm, that seems bad. Is just doing `print(unyt.micron)` sufficient to trigger the error you saw? If so we should probably fix this since people may not know how to adjust the unicode settings for their terminal. If you’d like please feel free to open a new issue with steps to reproduce the error (e.g. windows version, were you using powershell, cmd.exe, or something else). I have a windows machine I can test with.

**Comment by langmm** [comment]
I will test on my local windows boot and get back to you; so far I've only observed this on appveyor, but things are complicated there because Python output on appveyor is redirected (https://stackoverflow.com/questions/42644184/utf-8-in-appveyor-python-3-6). If its just an appveyor quirk it's probably OK, but if not I will open a new issue.

**Comment by ngoldbaum** [comment]
Ah I see, thanks for the additional context :)

**Comment by langmm** [comment]
Just confirmed that everything is fine when running on my local windows boot, so just an fun appveyor quirk.

If anyone comes across this same error the fix is to do ``chcp 65001`` and ``set PYTHONIOENCODING=utf-8`` before the installation, but this is exclusive to appveyor.
