### ISSUE TITLE
Checking units/dimension of dimensionless quantities

### ISSUE THREAD

**Issue by simfinite** [yt-project/unyt#146]
* unyt version: 2.7.1
* Python version: 3.7
* Operating System: Windows 10

First of all, thank you for this great Python package!

I am trying to use unyt's `returns` decorator to check dimensional correctness of some functions [as described in the documentation](https://unyt.readthedocs.io/en/stable/usage.html#checking-units). It works great, unless dimensionless quantities come into play:

With decorator `returns`:
```
@unyt.returns(unyt.dimensions.dimensionless)
def calc_b(a):
    return numpy.arcsin(a)

# Output: TypeError: result '1.5707963267948966' does not match 1
calc_b(1)    
calc_b(1*unyt.dimensionless)
```

Looking into the stacktrace, I found a quick fix that works for the given example:
If non-quantity objects are passed to `_has_dimensions` in unyt's `dimensions.py`, the dimension to compare with is set to `None` ([see here](https://github.com/yt-project/unyt/blob/711e2ebc22b59984fab1ee4dfcf745184bdb11dd/unyt/dimensions.py#L390)). If instead, non-quantities are assumed to be dimensionless, i.e. changing the referenced line to `arg_dim = dimensionless` the above example will work.

Not a sure if this is a valid solution though...

**Comment by ngoldbaum** [comment]
I think that's the correct fix. Would you like to put in a pull request so you get credit?

**Comment by simfinite** [comment]
Sure, here it is: https://github.com/yt-project/unyt/pull/147
