### ISSUE TITLE
bug: broken interaction between unyt_array and matplotlib imshow

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/unyt#161]
* unyt version: 2.7.2
* Python version: 3.8.2
* Operating System: MacOS

### Description

`matplotlib.pyplot.imshow` doesn't seem to play nicely with `unyt_arrays` like other plotting functions do.

I'm unsure if this is a unyt bug or a matplotlib bug, and I currently don't know how to disentangle them to know for sure.

### What I Did

```python
import unyt
import numpy as np
from matplotlib import pyplot as plt

arr = unyt.unyt_array(np.ones((16, 16)), "g/cm**3")
plt.pcolormesh(arr) # works
plt.contourf(arr) # work
plt.imshow(arr) # breaks
>> UnitOperationError: The <ufunc 'add'> operator for unyt_arrays with units "g/cm**3" 
(dimensions "(mass)/(length)**3") and "dimensionless" (dimensions "1") is not well defined.
```

**Comment by ngoldbaum** [comment]
Please report this to matplotlib, there’s nothing we can do about this in unyt.

**Comment by neutrinoceros** [comment]
Will do, thanks !
