### ISSUE TITLE
Passing an existing unyt_quantity to unyt_quantity does not preserve the original units.

### ISSUE THREAD

**Issue by l-johnston** [yt-project/unyt#177]
* unyt version: v2.8.0
* Python version: 3.8.6
* Operating System: Ubuntu 18.04

### Description

In my library a user can provide some parameters as either a float, with implied unit based on context, or a unyt_quantity. I thought I would be able to call unyt_quantity with the parameter without having to do type checking and end with the same value, but that's not the case.

### What I Did

```
>>> from unyt import mV, V
>>> unyt_quantity(1*mV, "V")
unyt_quantity(1, "V")
```

I expected to get unyt_quantity(0.001, "V")

This isn't necessarily a bug, but should unyt support this use case?

**Comment by ngoldbaum** [comment]
I think I’d prefer to raise an error maybe, suggesting to explicitly strip the units first. That’s just me though.

**Comment by l-johnston** [comment]
And you mean to error from within unyt? If so, how about attempting a conversion and allowing the error to occur there if appropriate?

**Comment by ngoldbaum** [comment]
It seems weird to me to ask for a quantity with a value of 0.1 mV in volts and more indicative of a code smell, the `unyt_quantity` initializer is for taking a scalar and applying units to it, not doing a unit conversion.

That said if it would make your life easier to make it do a unit conversion (and error out if the conversion doesn’t make sense dimensionally) then I think that’s probably not hurting anything and may make phrasing some operations that might be handed a scalar or a unit easier.

**Comment by l-johnston** [comment]
My library is an example of the latter, but I will do the type check instead. The final question is should unyt raise an error when given a unyt_array or do you prefer to close the issue?
