### ISSUE TITLE
Help wanted: How to define new unit with new dimension

### ISSUE THREAD

**Issue by gitFinancial** [yt-project/unyt#178]
* unyt version: Current
* Python version: Current
* Operating System: Windows

### Description

I want to know how how to define a new unit, which is unrelated to an existing unit dimension. For example, I would like to define a unit called 'USD' which is along a 'currency' dimension.

I already know how to define a new unit that is related to an existing dimension, such as:
```
u.define_unit('bbl', 158.9873 * L)
from unyt import bbl

However this does not relate to my use case.
```

### What I Did

```
I read the documentation but couldn't find a guide for this. I don't know what to do. Hopefully this is an easy question for someone to answer.
```

**Comment by ngoldbaum** [comment]
Right now there’s no API for defining user-defined dimensions.

**Comment by gitFinancial** [comment]
I'll use Pint instead, thanks.
