### ISSUE TITLE
Units dropped from output of numpy.around - is this normal?

### ISSUE THREAD

**Issue by caseyjamesdavis** [yt-project/unyt#182]
Hi all,

Thanks for this fantastic python library - it has really transformed my engineering analysis workflow.

Today, I noticed that when I pass a unyt quantity into **numpy.around** it only returns the number, not the typical _unyt_quantity(number, unit)_.  Is this the expected behavior?

Details are in the jupyter notebook screenshot below.

Cheers,
Casey

![image](https://user-images.githubusercontent.com/49321778/104248700-00028900-5438-11eb-9f58-fc5376f82c66.png)

**Comment by ngoldbaum** [comment]
To get this to work we would probably need to implement `__array_function__`, see https://github.com/yt-project/unyt/issues/139.

**Comment by ngoldbaum** [comment]
But yes, what you’re seeing is expected given that unyt doesn’t yet have an `__array_function__` implementation. Most numpy functions will treat unyt data as regular ndarrays. There are a few wrappers around numpy functions that preserve units in the top-level `unyt.array` namespace, see [the api docs](https://unyt.readthedocs.io/en/stable/modules/unyt.html).

**Comment by ngoldbaum** [comment]
The trchnical reason this doesn’t work is that `np.floor` is a ufunc, which we control via unyt’s `__array_ufunc__` implementation while `np.around` isn’t implemented as a ufunc and so needs to be wrapped by a new wrapping API that we don’t yet implement (it didn’t exist when we initially wrote unyt).

**Comment by ngoldbaum** [comment]
It probably makes sense to add a `unyt.array.uround` function.

**Comment by caseyjamesdavis** [comment]
Thanks for taking the time to explain and share the relevant links - it is much appreciated.

In my engineering analysis workflow I have been trying to develop an easy way to round long floats to a more realistic length for purpose of prettier printing in a jupyter notebook.

I have made a function that I use instead of **print** that will round a float to the desired number of digits and keep the unit from unyt.  It also appears to work with scientific notation.  See screenshot below.

![image](https://user-images.githubusercontent.com/49321778/104360726-82925380-54df-11eb-9c07-7fd9c870de59.png)

If you or anyone can think of a better way to do this I would  be interested in learning how.

Thanks again for this awesome tool!

Cheers,
Casey
