### ISSUE TITLE
Inconsistencies in raising MissingMKSCurrent ?

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/unyt#186]
* unyt version: current master (aaa2b244207c14c5f472214595a00201d105c0ae)
* Python version: 3.9.4
* Operating System: OSX

### Description

I think that there exist some inconsistencies in how the `MissingMKSCurrent` error is raised.

### What I Did

For instance, this is in line with the error class' docstring, which explains that 1 Ampere cannot be expressed in cgs.
```python
>>> import unyt as u
>>> u.unyt_quantity(1, "A**2").in_cgs()
```
```
~/dev/yt-project/unyt/unyt/unit_object.py in get_base_equivalent(self, unit_system)
    636             try:
--> 637                 new_units = unit_system[self.dimensions]
    638             except MissingMKSCurrent:

~/dev/yt-project/unyt/unyt/unit_systems.py in __getitem__(self, key)
    263             units = _get_system_unit_string(key, self.units_map)
--> 264             self.units_map[key] = parse_unyt_expr(units)
    265             return Unit(units, registry=self.registry)

MissingMKSCurrent: The cgs unit system does not have a MKS current base unit

During handling of the above exception, another exception occurred:

UnitsNotReducible                         Traceback (most recent call last)
<ipython-input-22-95905c004a29> in <module>
----> 1 u.unyt_quantity(1, "A**2").in_cgs()

~/dev/yt-project/unyt/unyt/array.py in in_cgs(self)
   1003         10.0 g/s**2
   1004         """
-> 1005         return self.in_base("cgs")
   1006
   1007     def in_mks(self):

~/dev/yt-project/unyt/unyt/array.py in in_base(self, unit_system)
    981             to_units, (conv, offset) = _em_conversion(u, conv_data, unit_system=us)
    982         else:
--> 983             to_units = self.units.get_base_equivalent(unit_system)
    984             conv, offset = self.units.get_conversion_factor(to_units, self.dtype)
    985         ret = self.v * conv

~/dev/yt-project/unyt/unyt/unit_object.py in get_base_equivalent(self, unit_system)
    637                 new_units = unit_system[self.dimensions]
    638             except MissingMKSCurrent:
--> 639                 raise UnitsNotReducible(self.units, unit_system)
    640         return Unit(new_units, registry=self.registry)
    641

UnitsNotReducible: The unit "A**2" (dimensions "(current_mks)**2") cannot be reduced to an expression within the cgs system of units.
```
However, and surprisingly, _this_ is apparently ok  ?
```python
>>> u.unyt_quantity(1, "A").in_cgs()
unyt_quantity(2.99792458e+09, 'statA')
```
Same goes with `"C**2"` (raises `MissingMKSCurrent`), while `"C"` doesn't (and is converted to "statC").

I stumbled upon this problem while attempting to optimise unyt's import time, which is currently crippled by nested try blocks.

**Comment by jzuhone** [comment]
My recollection is that it was nearly impossible to get those SI <-> cgs unit conversions involving EM quantities to work if anything other than a simple single unit was involved. So A works but not A^2. Most unit packages don't even try to do this conversion in any circumstance or (worse yet) they do it far too simply without recognizing that (for example) Tesla and Gauss are not the same dimensions even though they are both magnetic field units and they are related by a simple factor of 10^4.

I think what we need is a better error message.

**Comment by neutrinoceros** [comment]
> I stumbled upon this problem while attempting to optimise unyt's import time, which is currently crippled by nested try blocks.

an update is due here: I changed my mind about this. The actual issue is that building the unit registry takes up much too many deep copies. See #27 

> I think what we need is a better error message.

@jzuhone I think this would help indeed ! could you also explain what "statA" means here ?

**Comment by jzuhone** [comment]
statA is "statampere" or one statcoulomb per second: 

https://en.wikipedia.org/wiki/Statampere
https://en.wikipedia.org/wiki/Statcoulomb
