### ISSUE TITLE
Use pre-commit hooks to apply linting rules

### ISSUE THREAD

**Issue by matthewfeickert** [yt-project/unyt#193]
### Description

As noted in https://github.com/yt-project/unyt/pull/191#issuecomment-894608515 there are some PR that fail linter tests. As most of these linter tests just require a human to manually run a tool, like `flake8` or `black`, it seems like it would be helpful to use `pre-commit` hooks to run this for the user.

In my own projects what I've found super useful for keeping pre-commit hooks up to date and for saving time is to enable [pre-commit.ci](https://pre-commit.ci/) which will allow for pushes back to a PR if pre-commit hooks fail with attempts at resolving those failures.

There are some [examples over on the Scikit-HEP website](https://scikit-hep.org/developer/style#pre-commit) (in addition to all the examples the pre-commit team has).

**Comment by neutrinoceros** [comment]
We use pre-commit.ci for yt itself now, I think it is worth migrating to it for unyt to, in particular because it saves the trouble of syncing installed versions for linters for all devs.

**Comment by neutrinoceros** [comment]
CI is currently broken because black 22.1 made some intentional style changes that are not currently applied to unyt.
I'm going to pin it to the previous version in tex.ini for now but this is not a viable solution long term. Using `pre-commit.ci` would be much more viable.
