### ISSUE TITLE
BUG: can't easily access memory footprint of an array

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/unyt#198]
* unyt version: master (unyt-2.8.0+36.ga65c04c)
* Python version: 3.9.6
* Operating System: OsX

### Description

Currently `sys.getsizeof` doesn't work correctly on unyt arrays
```python
import sys
import numpy as np
import unyt as un

data = np.random.random_sample((512, 512, 512))
print(sys.getsizeof(data))

udata = data * un.s
print(sys.getsizeof(udata)) 
```

The two object should have very close size, a tiny bit over 1GiB (or 1024^3 = 1073741824)
```
1073741960
160
```
They don't.

Note that this looks very similar to what happens when inspecting the memory size of a view instead of the actual data container object:
```python
>>> class myarr(np.ndarray):
...         pass
>>> mdata = data.view(myarr)
>>> print(sys.getsizeof(mdata))
160
```
I'm hoping this is a trivial fix

**Comment by neutrinoceros** [comment]
ugh. After a little digging I don't think there's a way around that. Most, if not all  `unyt_array` instances are indeed views on `np.ndarray` objects, and I don't think it's worth implementing a `__sizeof__` that would violate the universal rule that `sys.getsizeof` should measure the object's intrinsic size, and none of its content. The idiomatic way to measure the footprint of an array `arr.size * arr.itemsize` works perfectly on views, hence on `unyt_array`s. I don't think there's anything to do here after all.

**Comment by matthewturk** [comment]
That will display the size of the view, but I think one can -- without too
much trouble -- construct views that obfuscate the true size.  I do agree
this is out of scope for the project, though, and we shouldn't violate
`__sizeof__` without good reason.
