### ISSUE TITLE
Subtracting temperatures gives degC rather than delta_degC 

### ISSUE THREAD

**Issue by harrysalmon** [yt-project/unyt#220]
* unyt version:
'v2.8.0'
* Python version:
3.8.12
* Operating System:
Mac

### Description

Working with change in temperature. I would expect a difference between two temperatures to return a delta_degC rather than a degC. 

### What I Did

Actual
```
>>> import unyt as u
>>> delta = 2 * u.degC - 1 * u.degC 
>>> delta 
unyt_quantity(1, 'degC')
>>> delta.to('K')
unyt_quantity(274.15, 'K')
```

Expected

```
>>> import unyt as u
>>> delta = 2 * u.degC - 1 * u.degC 
>>> delta 
unyt_quantity(1, 'delta_degC')
>>> delta.to('K')
unyt_quantity(1, 'K')
```

**Comment by neutrinoceros** [comment]
I agree that this feature is desirable. I'll think about how this could be implemented.

**Comment by l-johnston** [comment]
There is a workaround:
```python
In [1]: from unyt import degC, delta_degC
In [2]: dt = 20*degC - 10*degC
In [3]: dt
Out[3]: unyt_quantity(10, 'degC')
In [4]: dt.units = delta_degC
In [5]: dt
Out[5]: unyt_quantity(10, 'delta_degC')
```

Other technical computing systems such as Mathcad Prime and Matlab also have this trouble with temperature subtraction:
![temperature subtraction](https://user-images.githubusercontent.com/17813788/180611595-4eb13cb2-e05d-4158-b791-a11476aff620.png)

**Comment by neutrinoceros** [comment]
Furthermore I note that on the main branch (future unyt 3.0), `np.diff` behaves as we expect here
```python
>>> from unyt import K
>>> import numpy as np
>>> np.diff([1, 2, 3]*K)
unyt_array([1, 1], 'delta_degC')
```
But manual differences don't
```python
>>> 2*K - 1*K
unyt_quantity(1, 'K')
```
