### ISSUE TITLE
Can decorators accept multiple units?

### ISSUE THREAD

**Issue by gregsalvesen-work** [yt-project/unyt#221]
* unyt version: 2.8.0
* Python version: 3.9.10
* Operating System: macOS Big Sur

Is it possible to specify multiple allowable units for an argument to a function using the `@accepts` decorator? And similarly for the `@returns` decorator?

I want to use the same function to convert a linear frequency [1/s] to an angular frequency [rad/s], or a linear wavenumber [1/cm] to an angular wavenumber [rad/cm]. I want to check that this function accepts `lin` in units of either [1/s] or [1/cm], but am unsure how/if this can be accomplished.

```
import numpy as np
import unyt as u
def lin2ang(lin):
    """Convert a linear frequency (or wavenumber) to an angular frequency (or wavenumber)."""
    ang = lin * (2 * np.pi * u.rad)
    return ang
```

**Comment by neutrinoceros** [comment]
The `unyt.accepts` decorator doesn't support this usage at the moment.
I think you'd have to build a custom solution. How about something like this ?

```python
import numpy as np
import unyt as u
from unyt.dimensions import length, time

def lin2ang(lin):
    """Convert a linear frequency (or wavenumber) to an angular frequency (or wavenumber)."""
    if val.units.dimensions  not in (1/length, 1/time):
        raise TypeError(f"Input {lin!r} has invalid dimensions. Expected 1/length or 1/time.")
    ang = lin * (2 * np.pi * u.rad)
    return and
```

**Comment by neutrinoceros** [comment]
Closing since you seem to approve my solution.
