### ISSUE TITLE
The Thomson cross section attributes are misspelled

### ISSUE THREAD

**Issue by gregsalvesen-work** [yt-project/unyt#222]
* unyt version: 2.8.0
* Python version: 3.9.10
* Operating System: macOS Big Sur

This is incredibly minor, but the attributes for the non-relativistic electron scattering cross section named after J. J. Thomson are misspelled.

```
import unyt as u
print(u.sigma_thompson)
6.65245854533e-29 m**2
print(u.sigma_thomson)
AttributeError: module 'unyt' has no attribute 'sigma_thomson'
```

**Comment by neutrinoceros** [comment]
Good catch, I'll fix this. Thank you for reporting !
