### ISSUE TITLE
unyt should not have a single hard-coded metallicity value

### ISSUE THREAD

**Issue by jzuhone** [yt-project/unyt#229]
unyt uses a single value for the conversion from the ratio of metal mass to total mass to the solar value:

https://github.com/yt-project/unyt/blob/eb511a2a2455e1d2d2fbccdbfbff7b142cb5625f/unyt/_physical_ratios.py#L26-L27

Several studies have been carried out of Solar elemental abundances, which have different values. For example, the value used in X-ray astronomy from [Anders & Grevesse (1989)](https://ui.adsabs.harvard.edu/abs/1989GeCoA..53..197A) is closer to ~0.02. More recent studies have found something similar. Even Cloudy updates its abundance tables as well. 

Potential ways to include other options for solar metallicity measurements:

* Allow users to override the definition of `Zsun` using some function
* Provide a configuration system for unyt and include this as a configurable option (a big task which probably needs to have more reasons for having a configuration system than just solar metallicity).
* Open to other suggestions...

**Comment by neutrinoceros** [comment]
I agree that this alone doesn't justify adding a configuration system. Supporting a clean way to override a default at runtime seems like a good option.

**Comment by ngoldbaum** [comment]
Fixed by #315
