### ISSUE TITLE
MNT: setup pre-commit CI

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/unyt#236]
Following #193 and #232, we currently are *not* validating new contributions with flake8 and black as required. Pre-commit is now configured but not associated with any CI service. The goto option is still pre-commit.ci

@jzuhone

**Comment by jzuhone** [comment]
@neutrinoceros you know way more about this stuff than I do. any chance you can take a crack at it?

**Comment by neutrinoceros** [comment]
I would, but only an owner can do it. Signing up to pre-commit.ci takes only a couple clicks if I recall, but we need to log as a project owner. In any case it happens on their website.

**Comment by jzuhone** [comment]
@neutrinoceros ok, unyt has been added to pre-commit.ci

**Comment by neutrinoceros** [comment]
Thank you ! Let's close this then
