### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by kyleaoman** [yt-project/unyt#237]
The last release is ~15 months old. There are some useful bugfixes & updates in the meantime that it's difficult to take advantage of in public facing code that should assume people are installing from pypi. Time for a new release?

**Comment by jzuhone** [comment]
@kyleaoman yes, I agree with you. hoping to do this very soon but given there's limited person-power at the moment things have been slow going.

**Comment by jzuhone** [comment]
@kyleaoman I plan to cut a new release in the next two weeks.
