### ISSUE TITLE
Unexpected inequality

### ISSUE THREAD

**Issue by Shiina18** [yt-project/unyt#238]
* unyt version: 2.8.0
* Python version: 3.8.10
* Operating System: windows

```python
import unyt

unyt.define_unit('个', 1 * unyt.dimensionless)
unyt.define_unit('万', 10_000 * unyt.dimensionless)

4200 * unyt.个 == 0.42 * unyt.万  # True
0.42 * unyt.万 == 4200 * unyt.个  # False, expected True
0.42 * unyt.万 == 4200. * unyt.个  # False, expected True

(4200 * unyt.个).dtype  # int32
(4200. * unyt.个).dtype  # float64
(0.42 * unyt.万).dtype  # float64

(4200 * unyt.个).to(unyt.万).dtype  # float32
(4200. * unyt.个).to(unyt.万).dtype  # float64
(0.42 * unyt.万).to(unyt.个).dtype  # float64
```

**Comment by neutrinoceros** [comment]
Exact comparison with `==` isn't safe with float types. I don't think this can be "solved" within unyt. I suggest using the `numpy.testing` module for floating point comparison functions equipped with error margins.

**Comment by matthewturk** [comment]
Even so, I think it would be worthwhile to examine the exact difference -- do you think that you could convert them both to the same unit, and see what the absolute difference is?

**Comment by Shiina18** [comment]
> Exact comparison with `==` isn't safe with float types. I don't think this can be "solved" within unyt. I suggest using the `numpy.testing` module for floating point comparison functions equipped with error margins.

Thanks for the advice. `numpy.isclose` works well.

> Even so, I think it would be worthwhile to examine the exact difference -- do you think that you could convert them both to the same unit, and see what the absolute difference is?

```python
4200 * unyt.个 - 0.42 * unyt.万  # unyt_quantity(0., '个')
0.42 * unyt.万 - 4200 * unyt.个  # unyt_quantity(1.31130218e-08, '万')
```

Thanks for your reply. Now I get a clue how it goes. `a == b` while `b != a` looks counterintuitive at first glance, and it may be caused by different unit conversions and thus by the floating point nuisance.

**Comment by jzuhone** [comment]
Is there still an issue here that needs to be addressed?
