### ISSUE TITLE
Unit objects are not JSON serializable

### ISSUE THREAD

**Issue by majj** [yt-project/unyt#26]
* unyt version: 1.0.3
* Python version: 3.7
* Operating System: Windows 10

### Description

and 'TypeError: Object of type Unit is not JSON serializable' when works with serpy and pydantic

### What I Did

```
from unyt import mm

import json

json.dumps(mm)
```

Traceback (most recent call last):
  File "t24.py", line 12, in <module>
    json.dumps(mm)
  File "c:\python\python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "c:\python\python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\python\python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\python\python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Unit is not JSON serializable

**Comment by ngoldbaum** [comment]
Can you share a little bit more detail about what metadata you'd want in the json serialized output you're trying to create? I didn't anticipate that someone would want to dump a unit object to json like this.

**Comment by majj** [comment]
‘’‘

import pprint
import time

import unyt # pip install unyt
from unyt import mm, m, ft, km, hr
from unyt import s, ms, G


from pydantic import BaseModel, Schema # pip install pydantic
from pydantic import validator

class Tags(BaseModel):
    """ tags """
    
    eqpt_no:str
    
class Fields(BaseModel):
    """fields"""
    
    distance:float = Schema(1, title='distance', unit=km)
    speed:float = Schema(1, title='speed', unit=km/hr)
   
class Measurement(BaseModel):
    """ for influxdb measurement"""
    
    time:int = Schema(1, unit = ms)
    measurement:str
    tags:Tags
    fields:Fields
    

def test():    

    pprint.pprint(Measurement.schema())
    try:
        print(Measurement.schema_json(indent=2))
    except Exception as e:
        url = '''https://hynek.me/articles/serialization/'''
        print(e)

    tags = Tags(eqpt_no='Mts1')

    fields = Fields(distance=121, speed=23.2)

    mdata = Measurement(time=1000*time.time(), measurement='mts_station', tags=tags, fields = fields)

    print(mdata.json(indent=2))


if __name__ == '__main__':
    test()

‘’’

**Comment by ngoldbaum** [comment]
Hi I suspect there might be a language issue here. Unfortunately the code you shared doesn’t really help me. Can you explain in words what you’re trying to do?

**Comment by majj** [comment]
there is no unit for the measurement data (speed, distance,  electric current, etc. for example in automobile testing ) which storage in time series database(influxdb...), we need to define the metadata for the measurement  and sometimes we could convert the unit such as 'm' to 'ft',  and we hope the unit is serializable to be stored in db.

**Comment by ngoldbaum** [comment]
I don't think I'm going to implement this. It would be easier to just say str(Unit) if you really need a string unit name.
