### ISSUE TITLE
Is unyt supported for Python 3.7? (I got a SyntaxisError only with 3.7)

### ISSUE THREAD

**Issue by dprada** [yt-project/unyt#264]
* unyt version: 2.9.2 (last in conda-forge)
* Python version: 3.7
* Operating System: Ubuntu

### Description
I got the following error importing unyt with Python 3.7. With 3.8 and 3.9, everything is alright.
```
    from unyt.array import unyt_quantity
E     File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/unyt/array.py", line 1705
E       def __pow__(self, p, mod=None, /):
E                                      ^
E   SyntaxError: invalid syntax
````

**Comment by neutrinoceros** [comment]
No it's not. We dropped support for Python 3.7 in unyt 3.9.0
As of unyt 3.9.2, the minimal support version is Python 3.8, as you can see here
https://github.com/yt-project/unyt/blob/dcb321cf822d5d82c77be56243d78d470d96ee1e/setup.py#L50

**Comment by neutrinoceros** [comment]
I would be interested to know how you got unyt 2.9.2 to install on Python 3.7 however, as it shouldn't be possible.
If you got it via conda-forge then that's on us. There was a problem the first time the release was uploaded which may have caused it.
Did you use conda, and if so, when was it ?

**Comment by dprada** [comment]
Thanks @neutrinoceros!

Yes, via conda-forge. I just tried a minute ago from a conda env with Python 3.7. Look:

![image](https://user-images.githubusercontent.com/531231/182229356-65edc347-1c9c-4393-b012-f897778f4e37.png)

**Comment by neutrinoceros** [comment]
I suppose its offering the first (broken) iteration. I wasn't aware this would happen.
@jzuhone do you know if we can somehow yank/delete those broken builds on conda-forge ? I think unyt 2.9.0 and 2.9.2 (first build) are affected.

Anyway, thank you very much for reporting !

**Comment by neutrinoceros** [comment]
The request was accepted. Now the conda forge server correctly marks those builds as broken. I assume it means they won't be downloaded unless specifically requested, but could someone check before I close this ?

**Comment by neutrinoceros** [comment]
I checked myself, now installing unyt with Python 3.7 gets you unyt 2.8.0, which is the expected behaviour. Thanks again to @dprada for the report, much appreciated

**Comment by jzuhone** [comment]
@neutrinoceros thanks for handling this

**Comment by neutrinoceros** [comment]
my pleasure :)
