### ISSUE TITLE
Rename master to main?

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/unyt#275]
I'd like to rename the master branch to be main, following generally accepted practice these days. People with clones or forks of the unyt repo with WIP work might need to manually switch.

I'm assuming anyone that cares about this is following new issues. If you have a problem with doing this please comment below. If I don't hear objections I'll just go ahead and do it next week.

**Comment by matthewturk** [comment]
I strongly support this and am grateful for you taking this on.  Thank you,
Nathan!

**Comment by ngoldbaum** [comment]
This is done, please update your local clones.
