### ISSUE TITLE
Error in unit_symbols.py

### ISSUE THREAD

**Issue by DougAJ4** [yt-project/unyt#28]
In the mass symbols, the line for Mg is:
Mg = megagramme = tonne = metric_ton = Unit("kg")

I believe this should be:
Mg = megagramme = tonne = metric_ton = Unit("Mg")

**Comment by ngoldbaum** [comment]
Oops! Care to put in a PR with a fix?

**Comment by DougAJ4** [comment]
Sorry, but I have no idea how pull requests work, and having just read the tutorial, the whole thing seems even more confusing.
The fix is the bottom line in the original message.

**Comment by ngoldbaum** [comment]
Fair enough, I just wanted to give you the opportunity to get credit in the commit log for the fix. I’ll probably fix this later today.

**Comment by ngoldbaum** [comment]
Thank you for the report! 🎆 :+1: :tada:

This issue will be fixed in the next release.
