### ISSUE TITLE
TST: downstream instability

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/unyt#291]
### Description

looks like merging #200 caused a regression in yt
https://github.com/yt-project/yt/actions/runs/3223984952/jobs/5274634351

I'll take care of this today if I can

**Comment by neutrinoceros** [comment]
So the problem is that, in yt, some code has been written that _relies_ on the old behaviour of, say `np.dot`, dropping units on unyt arrays.

The code can (and likely should) be adapted on yt's side, but it seems to me that it'd be best to consider that a fully NEP 18 compliant version of unyt (as is being developed starting with #200, see #289), should be numbered `3.0.0` instead of `2.10.0`.
@ngoldbaum WDYT ?

**Comment by ngoldbaum** [comment]
Yes, definitely, the next release is unyt 3.0

**Comment by neutrinoceros** [comment]
Cool. I don't think there's any actionable left for now so I'll close this but just to make sure everybody is on the same page I'll ping @jzuhone
