### ISSUE TITLE
BUG: incorrect comparison with dimensionless quantities

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/unyt#307]
### Description

Two quantities with identical values but different units are considered different by the equality operator (`__eq__`) *except* if one of them is dimensionless.
I don't think think this behaviour is intended, or is it ?
In all cases it's the reason why the following test passes even when `np.around` is not in fact correctly supported
https://github.com/yt-project/unyt/blob/147ce9a4eeb3a2034cb9fad0290e40a52a1df761/unyt/tests/test_array_functions.py#L620-L624

### What I Did

```python
import unyt as u

assert 1 * u.g != 1 * u.cm # passes
assert 1 * u.Unit() != 1 * u.cm # AssertionError !
```

**Comment by ngoldbaum** [comment]
Yes, it seems this is on purpose, it's happening because of these lines: https://github.com/yt-project/unyt/blob/main/unyt/array.py#L1831-L1837.

In principle we could change this but I bet it would break code in yt.

**Comment by neutrinoceros** [comment]
thanks for pointing this out, I couldn't find where the behaviour was coming from. Welp, FWIW I'm doing regular updates in yt to keep up with the NEP 18 stuff here, because we are already constantly breaking stuff there, and yt currently forbids unyt 3.0 in prod (though the goal is of course to transition to `>=3.0` as smoothly as possible).

That said, I wasn't expecting this would be intended, and I don't think it should be changed at this point.
