### ISSUE TITLE
DOC: update needed on how to deploy

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/unyt#334]
### Description

Note to self that the "How to deploy" section in the dev guide https://unyt.readthedocs.io/en/stable/contributing.html#deploying
is out of date since it relies on `setup.py`, which was removed in #318
This won't be a blocker for bugfix releases (I'm about to deal with 2.9.3), but we need to deal with it for the next release that'll happen from the main branch (most likely 3.0)

Most likely we can leverage this workflow to automate the process and not have to worry about this: https://github.com/pypa/gh-action-pypi-publish

**Comment by neutrinoceros** [comment]
we can also get rid of the `--universal` flag for `bdist_wheel` since we dropped support for Python 2

**Comment by ngoldbaum** [comment]
You still need `—universal` to only upload one wheel per python version.

**Comment by neutrinoceros** [comment]
I for one didn't use it for the 2.9.3 release, but maybe I still got the effect because it's configured in `pyproject.toml` ?

**Comment by ngoldbaum** [comment]
makes sense

**Comment by neutrinoceros** [comment]
actually I doubt that this is needed now. I just tried building wheels locally with `python -m build`

If I keep the `universal` option in `pyproject.toml` I get a file named
```
unyt-2.9.2.post274+gc03513b-py2.py3-none-any.whl
```

which misleadingly seems to imply that Python 2 is supported. If I remove this option I still get a single wheel, and it's not attached to a specific Python 3 version:
```
unyt-2.9.2.post274+gc03513b.d20221207-py3-none-any.whl
```

I'll remove it in #337
