### ISSUE TITLE
Cannot import some common units

### ISSUE THREAD

**Issue by samgdotson** [yt-project/unyt#370]
* unyt version: 2.9.4
* Python version: 3.9.12
* Operating System: Windows 10, Ubuntu 22.04

### Description

`unyt` cannot import some units that are in the unit lookup table. 

```py
In [1]: from unyt import L
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from unyt import L

ImportError: cannot import name 'L' from 'unyt' (C:\Users\samgd\anaconda3\lib\site-packages\unyt\__init__.py)
```

Other units that cannot be imported include:
[MMBTU, Wh, therm, quad] -- these units were added in PR #294 and may not have been included in the most recent release. Although not being able to import liters is surprising.

Edit to add that none of the aliases for these units work, either.

**Comment by neutrinoceros** [comment]
sorry #294 hasn't been released yet. We're planning for the next non-bug fix release to be a major one and it's time consuming.

**Comment by ngoldbaum** [comment]
Yeah, sorry, Liter was an oversight, it should have been included from the beginning.

I'm going to close this since those units are defined in main, they just haven't made it to a release yet.
