### ISSUE TITLE
implementation question: possible to subclass the unyt array type?

### ISSUE THREAD

**Issue by zingale** [yt-project/unyt#39]
We currently have a data type `ArrayIndexer` that is built from subclassing `np.ndarray`:

https://github.com/zingale/pyro2/blob/master/mesh/array_indexer.py

We do this to add methods that we wanted for basic finite-difference operations and boundary conditions for our code.  

Is there an easy way to subclass `unyt_array` just like one would for `np.ndarray`?  We'd like to be able to add units to our type.

It maybe that what we are doing is not the best approach anyway, so if there is better way to add methods to the `unyt_array`, we're happy to hear that as well.

**Comment by ngoldbaum** [comment]
It looks like your subclass just attaches metadata to the array, I think it should work without too much hassle. I'd do this by overriding `__new__` and `__array_finalize__` in your subclass but make sure to call those methods on the superclass explicitly.

For inspiration you can look at `ImageArray` in yt, which is a subclass of `YTArray` and will be a subclass of `unyt_array` in yt 4.0. We also explicitly test that subclassing works correctly (at least in a limited sense):

https://github.com/yt-project/unyt/blob/master/unyt/tests/test_unyt_array.py#L1179

If you run into issues please let us know.

**Comment by zingale** [comment]
Thanks Nathan.
