### ISSUE TITLE
Import time is very long (20 seconds) on Amazon Linux 2

### ISSUE THREAD

**Issue by sidfeiner** [yt-project/unyt#411]
* unyt version: 2.9.5
* Python version: 3.9
* Operating System: Amazon Linux 2 (x86_64 and arm)

### Description

Importing `import unit as u` takes around 20-22 seconds.
When I run the code locally on a Macbook Pro with an M1 chip, the import is pretty instant.
I haven't debugged it very deeply, but seems like most of the time is spent during the following:
`from unyt import physical_constants`

### What I Did

```
import unit as u
```

**Comment by ngoldbaum** [comment]
There's been some work recently to improve import time since the last release. Can you try again with unyt built from the main branch?

unyt needs to import (some subsets of) sympy and numpy, so there's a limit to how much we can improve this.

**Comment by sidfeiner** [comment]
I actually increased the memory to 2GB (default is apparently 128 MB) and it already decreased the import time to 5 seconds, so I guess that's the direction I should go in :)
Thanks!

**Comment by ngoldbaum** [comment]
closing but feel free to reopen if you want to continue this

**Comment by neutrinoceros** [comment]
Just to give additional pointers on this:
Indeed there's one unreleased optimization still, that is: if matplotlib is installed, it won't be imported alongside unyt. In environments without matplotlib, the next release won't be faster to import.

Sympy and numpy don't implement lazy loading, so it's all or nothing, hence we're bound to import them whole before unyt, and it currently takes about 60% of unyt's total startup time.

Indeed unyt.physical_constants is still pretty long to start. Watch out for the next sympy release, it will make it faster.

And in case you want to profile import times more precisely in the future, I recommend this tool: https://pypi.org/project/tuna/
