### ISSUE TITLE
Microseconds?

### ISSUE THREAD

**Issue by dangom** [yt-project/unyt#47]
* unyt version: 1.0.6
* Python version: 3.6.6
* Operating System: macOS 10.13.6

### Description

I see nanoseconds and milliseconds work, but there are no microseconds.

### What I Did

```
import unyt as u
(40*u.s).to(u.microsecond)
```

**Comment by ngoldbaum** [comment]
Oops! See #48.

**Comment by ngoldbaum** [comment]
And see #34 which might also be annoying. I do want to fix that but it will take a little bit more care because of Python 2.7 I think.

**Comment by dangom** [comment]
Thanks for the quick response.

**Comment by dangom** [comment]
(and of course, thanks for the project!)
