### ISSUE TITLE
argsort returns array of zeros

### ISSUE THREAD

**Issue by brittonsmith** [yt-project/unyt#51]
* unyt version: 1.0.7
* Python version: 3.6.6
* Operating System: Mac OS 10.12.6

### Description

The argsort function returns an array of all zeros with units when operating on a `unyt_array`. Beside being all zeros, I would expect the returned array to be unitless.

### What I Did

```
>>> import numpy as np
>>> import unyt
>>> q = unyt.unyt_array(np.random.random(10), "g")
>>> q.argsort()
unyt_array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'g')
>>> np.argsort(q)
unyt_array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'g')
```

Not sure if this helps, but in `yt`, I get the following:
```
>>> import numpy as np
>>> import yt
>>> q = yt.YTArray(np.random.random(10), "g")
>>> q.argsort()
YTArray([8, 1, 5, 9, 2, 0, 4, 3, 7, 6]) g
```

The values are correct, but the returned array also has units, which I would not expect.

I'm happy to take a deeper look if someone can point me in the right direction.

**Comment by ngoldbaum** [comment]
I usually debug issues like this by putting a breakpoint in `__array_ufunc__`. Note that importing unyr calls that function a few times so look at the backtrace to be sure argsort is in the call stack. If `__array_ufunc__` isn’t getting called try `__array_finalize__`. If *that* doesn’t get called I’m not sure what to do. I can take a look at this on Tuesday :)

**Comment by brittonsmith** [comment]
``__array_ufunc__`` does not get called, but `__array_finalize__` does. However, even with a breakpoint in there, the backtrace I get is not helpful. It actually says the line of origin is `q = yt.unyt_array(np.random.random(10), "g")` even when I've put code in between that line and `q.argsort()` that I've seen being executed.

I am likely missing something, but I don't know where else to look. Perhaps the solution is to simply write a `unyt_array.argsort` method that passes the array view. I'm happy to do this if you think it's the best way forward.

Also, this is not urgent. It's easy enough to call `q.v.argsort()` instead of `q.argsort()`.
