### ISSUE TITLE
Should `apply_over_axes` "ignore" units?

### ISSUE THREAD

**Issue by kyleaoman** [yt-project/unyt#545]
This is a question more than a bug.

The current unyt implementation of numpy's `apply_over_axes` is:

```
@implements(np.apply_over_axes)
def apply_over_axes(func, a, axes):
    res = func(np.asarray(a), axes[0]) * a.units
    if len(axes) > 1:
        # this function is recursive by nature,
        # here we intentionally do not call the base _implementation
        return np.apply_over_axes(func, res, axes[1:])
    else:
        return res
```

This assumes that the function `func` preserves the units of the input `a`. It looks like it's necessary for `func` to return values with common units, but I guess those don't strictly need to be the same as those of `a`? As a trivial example, shouldn't:
```
def f(x):
    return x ** 2
```
be allowed? In this case the result will be incorrect. Is the following implementation enough?

```
@implements(np.apply_over_axes)
def apply_over_axes(func, a, axes):
    res = func(a, axes[0])
    if len(axes) > 1:
        # this function is recursive by nature,
        # here we intentionally do not call the base _implementation
        return np.apply_over_axes(func, res, axes[1:])
    else:
        return res
```

**Comment by neutrinoceros** [comment]
> shouldn't:
>```python
> def f(x):
>    return x ** 2
>```
>be allowed?

It should actually not: `np.apply_over_axis` only accepts function that have 2 arguments, where the second one must be an axis. 

> In this case the result will be incorrect.

I'm not sure what you meant here.

**Comment by neutrinoceros** [comment]
indeed it should. Thanks for clarifying. I now agree that unyt's implementation of `apply_over_axis` shouldn't be concerned with units, as it's both out of its hands and not its responsibility. I'll accept a PR with your proposed change, which makes a lot more sense. Thanks !
