### ISSUE TITLE
BUG: numpy function `take` strips units with scalar index input

### ISSUE THREAD

**Issue by kyleaoman** [yt-project/unyt#549]
* unyt version: 3.0.3
* Python version: 3.12
* Operating System: Linux (Fedora 40)

### Description

The numpy function `take` strips units when a scalar index (rather than array-like) is passed.

### What I Did

```
>>> a = [1, 2, 3] * u.cm
>>> a.take([0])  # OK
unyt_array([1], 'cm')
>>> np.take(a, [0])  # OK
unyt_array([1], 'cm')
>>> a.take(0)  # not OK
np.int64(1)
>>> np.take(a, 0)  # not OK
np.int64(1)
```

**Comment by kyleaoman** [comment]
Yes possibly, but I'm now on xmas holiday, so maybe not soon :)

**Comment by neutrinoceros** [comment]
No worries. Happy holidays !
