### ISSUE TITLE
[feature request] Kilocalorie and Kilojoule + metric prefix grammar support

### ISSUE THREAD

**Issue by justinGilmer** [yt-project/unyt#66]
* unyt version: `1.0.7`
* Python version: `3.5.5`
* Operating System: `MacOS 10.14.3`

### Description

In my field of study, some common units that we operate in are kilocalorie and kilojoules. `unyt` supports `calorie` and `joule`, but there is no equivalent currently for `kcal` and `kJ`

I would love to see either those added as kilo-prefixed units, or is there a plan to support grammars like `u.kcal` which translates to 1000*`u.calorie`?

This would help us quite a bit in our current project, where we are desiging the library with units in mind from the start, to remove the need to add in arbitrary manual conversions like `property_in_m = 1e-3 * property_in_mm`.

I think that feature would be super useful in general, being able to prefix a unit with a metric prefix would be awesome.

Maybe I have missed that feature, if so, id love to know how to do this!

**Comment by ngoldbaum** [comment]
This is being worked on, see #65. I'm hoping to release unyt 2.0 very soon with this new feature and several other nice features.

**Comment by ngoldbaum** [comment]
Also I'm pretty sure `unyt.unit_object.Unit('kcal')` does work, it's just that not all of the units are exposed in the `unyt` namespace. This is fixed by #65.

**Comment by justinGilmer** [comment]
Hah that is insanely well timed 😃   

Thanks for the quick response! This is excellent news!

**Comment by ngoldbaum** [comment]
This should work on master now.
