### ISSUE TITLE
[feature request] Significant Figures

### ISSUE THREAD

**Issue by sharkweek** [yt-project/unyt#67]
It would be super useful to have some sort of function or decorator that would allow for performing units calculations while respecting the significant figures of the inputs.

**Comment by ngoldbaum** [comment]
I don't quite understand what that means. Can you make a short concrete example of what you'd like to do?

**Comment by sharkweek** [comment]
Sure! I'm referring specifically to value precision. If, say, I am multiplying two sets of numbers of differing precision, the function would return a value rounded to the precision of the _least_ precise value.

`2.0 * 2.015739845`, for example, would yield `4.0`.

**Comment by ngoldbaum** [comment]
Is there a way to do that already using numpy?

**Comment by ngoldbaum** [comment]
Because if there is it should "just work" with unyt.

We don't have a concept of precision or uncertainty in unyt right now. I think it might require adding that for this to make any sense.

**Comment by sharkweek** [comment]
Ah, okay.

Full disclosure: I'm a mechanical engineer fumbling through Python, but to my knowledge, numpy does not have a function for that. The best thing I've found is this [repo](https://github.com/odysseus9672/SELPythonLibs) with a `SigFigRounding.py` that could work.
