### ISSUE TITLE
Using np.linalg.inv with unyt_array has no effect on units

### ISSUE THREAD

**Issue by sharkweek** [yt-project/unyt#69]
* unyt version: 1.0.7
* Python version: 3.6
* Operating System: Windows 10

### Description

Using the `numpy.linalg.inv()` to calculate the inverse of a matrix, doesn't affect units.

### What I Did
Here is what happens when you take the inverse of an `unyt_array`:
```
>>> x = unyt.unyt_array([[1. , 0.5, 0.5],
                         [0.5, 1. , 0.5],
                         [0.5, 0.5, 1. ]],
                        'psi')
>>> np.linalg.inv(x)
unyt_array([[ 1.5, -0.5, -0.5],
            [-0.5,  1.5, -0.5],
            [-0.5, -0.5,  1.5]], 'psi')
```
`numpy` correctly carries out the inverting operation, but the units remain the same where they should now be the reciprocal of the original units (`'inch**2/lbf'` in this case). As of now, the only work around I can think of is to create a new `unyt_array` with the inverted value of the original one and the reciprocal of the original's units.

**Comment by ngoldbaum** [comment]
So I doubt there's anything we can do about making `np.lingalg.inv` respect units correctly without support in NumPy for `__array_function__`, which is being added in a future numpy release. I don't see any mention of `lingalg.inv` in [NEP-18](https://www.numpy.org/neps/nep-0018-array-function-protocol.html) but maybe @shoyer knows more?

We could also define a wrapper around `lingalg.inv` that correctly handles units and add the wrapper to `unyt`.

**Comment by shoyer** [comment]
Every function that accepts arrays or array-like objects in NumPy's public APIs will support NEP 18. That includes `np.linalg.inv`.

**Comment by sharkweek** [comment]
That's good news. I suppose we just have to wait until the numpy release that implements `__array_function__`.
