### ISSUE TITLE
cannot format `unyt_quantity` on older numpy versions

### ISSUE THREAD

**Issue by berceanu** [yt-project/unyt#89]
* unyt version:2.2.0
* numpy 1.13.3
* Python version: 3.6.8
* Operating System: Ubuntu 18.04

```python
import unyt as u

a = u.unyt_quantity(3., 'cm')
test = f'{a:.2f}'
```

```python
Traceback (most recent call last):
  File "LaserWakefieldAcceleration.py", line 170, in <module>
    test = f'{a:.2f}'
  File "/home/berceanu/anaconda3/envs/signac-driven-fbpic/lib/python3.6/site-packages/unyt/array.py", line 545, in __format__
    ret = super(unyt_array, self).__format__(format_spec)
TypeError: unsupported format string passed to unyt_quantity.__format__
```
However this works with `numpy 1.16.2`.

**Comment by ngoldbaum** [comment]
In order for this to work you'll need NumPy 1.14 or newer. This was implemented on the NumPy side here: https://github.com/numpy/numpy/pull/9883.

**Comment by berceanu** [comment]
But then shouldn't there be a requirement for numpy >= 1.14? Or at least a meaningful error message? :)

**Comment by ngoldbaum** [comment]
I could bump the minimum required numpy version but it’s just this one thing that doesn’t work. A meaningful error message would required checking the numpy version and shape of the array every time format gets called, which I’d prefer to avoid for performance reasons.

**Comment by berceanu** [comment]
A mention in the docs then? :)

**Comment by ngoldbaum** [comment]
Sure, PRs welcome :)
