### ISSUE TITLE
Docstring example

### ISSUE THREAD

**Issue by berceanu** [yt-project/unyt#97]
What is the recommended way to write a docstring for a function `foo(a, b)` where the parameters are floats with units of say, mass and time?

**Comment by ngoldbaum** [comment]
I don't think we have a convention for that beyond just noting it in the docstring. What were you thinking?

**Comment by berceanu** [comment]
Sorry, I didn't explain myself. Let's say one is using `unyt` as part of a larger Python library, which is using [`numpydoc`](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard) for the docstrings.

The guidelines specify how the parameters should be described, for example:

```
Parameters
----------
filename : str
copy : bool
dtype : data-type
iterable : iterable object
shape : int or tuple of int
files : list of str
```

So my question is, how should a parameter with units be specified? Maybe 

```
Parameters
----------
x : float with units of length
```

or

```
Parameters
----------
x : unit_quantity(float, length)
```

?

**Comment by ngoldbaum** [comment]
I don't really have a strong opinion here. Maybe note it in the description of the parameter?

```
Parameters
----------

mass: unyt_quantity or float
    A quantity with dimensions of mass. If passed in as a float, masses are assumed to be in kilograms.
```

**Comment by berceanu** [comment]
I'm just thinking this should be somehow standardized, so all libs depending on `unyt` can use the same style.

**Comment by ngoldbaum** [comment]
I was going to suggest looking to astropy's guidelines but it looks like they [don't have suggestions about this either](http://docs.astropy.org/en/stable/development/docrules.html).

What benefits do you see that will come about by advertising such a standard in our documentation?

**Comment by berceanu** [comment]
Making it easier for contributors to join projects that depend on `unyt`. Just like numpy-style docstrings have become the de-facto standard in the PyData world.

**Comment by berceanu** [comment]
Do you see any potential drawbacks?

**Comment by ngoldbaum** [comment]
Not really just I'm not sure it's worth the effort. If you want to suggest something to go in the docs, go ahead.

**Comment by berceanu** [comment]
Hm, after seing your example I think this might not be so simple. For instance, you assume your function can also take unitless quantities, which are being assigned a default unit, whereas I always require units. Coming to a standard might not be so easy after all :)
